CREATE TABLE TOASTUSER(
 USERID VARCHAR2(20) NOT NULL,
 PASSWORD VARCHAR2(20) NOT NULL,
 NICKNAME VARCHAR2(50) NOT NULL,
 ADDRESS VARCHAR2(100),
 PHONE VARCHAR2(20),
 EMAIL VARCHAR2(50) NOT NULL,
 AUTH  CHAR(1) NOT NULL,
 REGDATE DATE NOT NULL,
 PRIMARY KEY(USERID) 
);