CREATE TABLE TOASTCAL(
	CALID NUMBER(20),
	CALTITLE VARCHAR2(50),
	CALCONTENT VARCHAR2(200),
	USERID VARCHAR2(20),
	CALTYPE VARCHAR2(10),
	PRIMARY KEY(CALID)
);

CREATE SEQUENCE TOASTCAL_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO TOASTCAL 
	VALUES(TOASTCAL_SEQ.NEXTVAL,
			'4월달시간표','으아아아','HAPPY','month');
		
CREATE TABLE TOASTVISIT(
	SEQ NUMBER NOT NULL,
	VDATE DATE NOT NULL, -- 접속 시간(로그인 시간)
	USERID VARCHAR2(20), -- 로그인 ID
	BROWSER VARCHAR2(300), -- 접속 브라우저(헤더정보)
	CONSTRAINT VISIT_PK PRIMARY KEY(SEQ)
);

CREATE SEQUENCE VISIT_SEQ START WITH 1 INCREMENT BY 1;
			
CREATE TABLE TOASTUSER(
 USERID VARCHAR2(20) NOT NULL,
 PASSWORD VARCHAR2(100) NOT NULL,
 NICKNAME VARCHAR2(50) NOT NULL,
 ADDRESS VARCHAR2(100),
 PHONE VARCHAR2(20),
 EMAIL VARCHAR2(50) NOT NULL,
 AUTH  CHAR(1) NOT NULL,
 REGDATE DATE NOT NULL,
 PRIMARY KEY(USERID) 
);

/* 스케쥴타입 추가 = 회사,가족,ETC 등 해당 목록에 관한것들, STATE 길이 10으로 증가*/
CREATE TABLE TOASTSCHEDULE(
	SCHEDULEID      NUMBER,
	CALID    		NUMBER(20),	
	TITLE    		VARCHAR(50),
	CONTENT         VARCHAR(200),
	ISALLDAY 		CHAR(1),
	STARTDAY 		DATE,
	ENDDAY  		DATE,
	COLOR    		VARCHAR2(10),
	STATE    		VARCHAR2(10),	
	SCHEDULETYPE	NUMBER(1)
);